wurstscript/WurstScript

- EclipseWurstPlugin/src/de/peeeq/eclipsewurstplugin/console/WurstREPL.java
- EclipseWurstPlugin/src/de/peeeq/eclipsewurstplugin/ui/ExtractJurstCommand.java
- Wurstpack/wehack.lua
- de.peeeq.wurstscript/.classpath
- de.peeeq.wurstscript/build-jar.xml
- de.peeeq.wurstscript/src-test/tests/wurstscript/tests/MpqTest.java
- de.peeeq.wurstscript/src/de/peeeq/wurstio/Main.java
- de.peeeq.wurstscript/src/de/peeeq/wurstio/map/importer/ImportFile.java
- de.peeeq.wurstscript/src/de/peeeq/wurstio/mpq/Jmpq3BasedEditor.java
- de.peeeq.wurstscript/src/de/peeeq/wurstio/mpq/MpqEditorFactory.java
- de.peeeq.wurstscript/src/de/peeeq/wurstio/objectreader/WCTFile.java
- de.peeeq.wurstscript/src/de/peeeq/wurstscript/RunArgs.java
Important features:
-Decreased ram usage significantly
-Can open and rebuild mpqs including files that are compressed using other compression algorithms as zlib
-Much more stable implementation and cleaner code -> easy to add features
-Better resulting filesize
I've been testing Jmpq-v3 the last few days on different maps without problems so far. 
Since v3 was intended to replace v2 iam not going to fix any bug in v2. So the tickets: #327 #321 #355 and #323 can be closed.
> Added JMpq-v3 support

- Wurstpack/wurstscript/lib/systems/Damager.wurst
Damage actually don't works with just 1 factor
```
// example
var d = new Damager()
d.factor(UNIT_TYPE_STRUCTURE, 2)
d.damageTarget(u1, u2, 50) // deal 50 (not 100) damage to structures
```
> Fix Damager system

- Wurstpack/wurstscript/lib/systems/OnUnitEnterLeave.wurst
- fixed leave detection in general (leaving units were not detected due to wrong event response)
- fixed leave detection on preplaced units (wasnt working at all, wrong event response)
- removed the minimal unit indexer, it doesnt belong here and there is a real unit indexer in the stdlib which is 100% compatible
> Fixed leave-detection

- Wurstpack/wurstscript/lib/small helpers/ClosureForGroups.wurst
this is consistent with, e.g. handles/Unit.wurst
> add forUnitsInRange overload that does not use vec2

- Wurstpack/wurstscript/lib/math/Vectors.wurst
this method was previously using airAngle as 0 for vertical and PI/2
for horizontal. Clearly this is the design of a madman. I can see that
(from hudson) the only project currently using polarProject method is
Forest Defense, but it uses airAngle=0, so I amguessing that frotty has
already fixed this bug in STL2.
> [stl] fix the vec3.polarProject method

- de.peeeq.wurstscript/parserspec/jass_im.parseq
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/CompiletimeFunctionRunner.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/Main.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/BuildMap.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunMap.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/interpreter/ProgramState.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/interpreter/State.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtojass/ImAttributes.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ExprTranslation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/FunctionFlagCompiletime.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/FunctionFlagEnum.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ImTranslator.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/WurstScriptTest.java
Old rule:
- first all compiletime expressions are executed
- then compiletime functions
- no other order contraints specified
New rule:
- compiletime expressions and functions interleaved
- guaranteed that compiletime stuff in imported packages is executed first
- inside a package it should be top down (according to AST order)
Still untested, so do not merge before testing it.
> Changed order of compiletime execution (WIP)

- de.peeeq.wurstscript/src/main/antlr/de/peeeq/wurstscript/antlr/Wurst.g4
- de.peeeq.wurstscript/src/main/antlr/de/peeeq/wurstscript/jurst/antlr/Jurst.g4
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/attributes/IntVal.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/utils/Utils.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/JurstTests.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/ParserTests.java
I think this would parse ascii-chars (as in #585) correctly, but it is not backwards-compatible (`'\'` was a valid char before, but it is no longer valid.
@Frotty I let you decide if you want to merge this breaking change. If you merge it, you have to fix the StdLib as well.
I tried to follow the [rules in Pjass](https://github.com/lep/pjass/blob/master/token.l), so I hope it is compatible with Jass now.
> fix ascii-int parsing (#585)

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/ImInliner.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/OptimizerTests.java
Adds `@inline` and `@noinline` for customizing the inliner behavior.
Additionally, calls with constant arguments have a x2 Threshold for being inlined.
Also added `error` to functions which shouldn't be inlined.
**Note:** No errors or feedback if added on uninlinable func yet.
https://github.com/wurstscript/WurstScript/issues/300
> Add inliner annotations and threshold modifier for funcs with constant args

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/providers/GroupProvider.java
It no longer removes the unit from the group - just like it's jass counterpart
Minimal example:
```
function foo() returns bool
let u = createUnit(players[0], 'hfoo', vec2(0, 0), angle(0))
let g = CreateGroup()
g.addUnit(u)
FirstOfGroup(g)
return not g.isEmpty()
@test function test_foo()
assertTrue(foo())
init
print(foo())
```
Used to print True in game, but the unit test failed
> Fix compiletime implementation of FirstOfGroup

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/validation/WurstValidator.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/BugTests.java
Right now this throws a warning:
```wurst
class A
var i = 0
construct()
this.i = this.i // warning
```
However this will not:
```wurst
init
var i = 0
i = i // no warning
print(i)
```
It works for class members, but not locals. By debugging I found out that in the [validator](https://github.com/wurstscript/WurstScript/compare/fix-assignment-no-effect-warning?expand=1#diff-1876af8b02722f4f9605e5b2450570d6R787) the namelinks for the local scenario don't have the same identity and thus the `==` check failed. It seems to work with the defs tho. 
But idk if this is the 'correct' fix @peq 🤷‍♂️
> Fix missing i = i warning for locals

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/CompiletimeFunctionRunner.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/WurstCompilerJassImpl.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunTests.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/ILconstObject.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/interpreter/EvaluateExpr.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/interpreter/ProgramState.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtojass/ImAttrType.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtojass/ImAttributes.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/EliminateClasses.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ImPrinter.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/types/TypesHelper.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/CompiletimeTests.java
Currently trying if this works ...
> WIP: support for persisting objects in compiletime expressions

- de.peeeq.wurstscript/parserspec/wurstscript.parseq
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/WurstCompilerJassImpl.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/ConfigProvider.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/WurstCommands.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/WurstLanguageServer.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/BuildMap.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/MapRequest.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunMap.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/RunArgs.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ClosureTranslator.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/types/TypesHelper.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/utils/Utils.java
Corresponding plugin update on branch https://github.com/wurstscript/wurst4vscode/tree/jhcr-commands
This adds 2 commands to vscode:
- Start a map with JHCR (will insert code for activating JHCR into the mapscript and runs `jhcr init` on the mapscript before injecting it into the map)
- Reload JHCR code (will rebuild the mapscript and run `jhcr update`)
TODO:
> WIP: Jhcr integration

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/ConfigProvider.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunMap.java
Added a way to set custom wc3 run arguments for the run map command via vscode settings.
If this merged, should also update the vscode plugin.
> Custom wc3 run arguments

- de.peeeq.wurstscript/build.gradle
- de.peeeq.wurstscript/src/main/java/de/peeeq/datastructures/Worklist.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/LocalMerger.java
- using immutable collections to share data between nodes in the graph
- better strategy for calculating fixed point
> improved performance for liveness calculation in LocalMerger

- de.peeeq.wurstscript/parserspec/jass_im.parseq
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/ImInliner.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ImPrinter.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ImTranslator.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/StackTraceInjector2.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/BugTests.java
The stack trace injector would add parameters to functions that were
called with ExecuteFunc, which is not allowed. With this changed it is
now handled similar to function references by adding a bridge function.
See #920
> Fixed a bug with ExecuteFunc and stacktraces

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/attributes/AttrExprType.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/BugTests.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/JurstTests.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/WurstScriptTest.java
> Allow equality checks between agent types

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/ModelManagerImpl.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/WurstWorkspaceService.java
these messages aren't needed any longer as we haven't had model issues for a while. They make up the majority of the log.
> Reduce log spam

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/validation/ValidateClassMemberUsage.java
fixes https://github.com/wurstscript/WurstScript/issues/953
> Omit unused warning from private static functions with compiletime annotation

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/objectreader/ObjectTable.java
Simplest fix for #984, based on [these few comments](https://github.com/wurstscript/WurstScript/commit/aadcf2905d4fab61ee6c05a010a3393cb29fc86c#diff-a431aa1b9398e51369f3b3d4418b9f3c1804c503269b3a3f6f6e8f936e57bf67L18). If this is all that's needed, great! If you had other plans for this fix or wanted to include some more changes, please feel free to close this PR.
Also changed `Map` to `LinkedHashMap` per @peq's comment, to keep the order deterministic.
> Use original object ID if new object ID is 0

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/ExprTranslation.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/LuaTranslationTests.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/WurstScriptTest.java
- de.peeeq.wurstscript/src/test/resources/QuickTestsSuite.xml
replaces null strings with empty strings in lua
Null strings will cause errors when used in lua natives.
Fixes one of the issues reported in #885 .
> fix lua null string

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/ExprTranslation.java
In lua, init blocks result in incorrect map scripts, if the package ErrorHandling is not used.
In particular, the print function inside the error function will be "$debugPrint". The $ character causes the map to not load.
This change is based on the jass expression translation here: [ExprTranslation.java](https://github.com/wurstscript/WurstScript/blob/e25c260b65dcb3186cb9c6ec1e9cb44c78bb7b0d/de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtojass/ExprTranslation.java#L28)
This change only has an effect if ErrorHandling is not used. Then the call to "$debugPrint" is replaced with "BJDebugMsg" like in the jass expression translator.
> lua: use BJDebugMsg for error messages if not using ErrorHandling package

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/validation/WurstValidator.java
When only configured functions (functions that are overridden by the config package) are used, Wurst will consider the configured package unused. In other cases, the function is not considered to be unused, but will be attributed to the wrong package, resulting in "the import ... can be removed, because it is already included in ...".
This can be fixed by implicitly adding the configured package to the used packages, when the config package is used.
A prime example is the ErrorHandling package. In most cases, only the configurable error function is used, so when this function is configured  most packages that import ErrorHandling will throw a warning.
> fix unused import warning with configured packages

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/attributes/InitOrder.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/ConfigPackageTests.java
Fix for #990 .
There is an implicit initialization order dependency between the config and configured package:
The config package is always initialized directly before the configured package. However, this dependency is not known to the wurst validator, so it is possible to create cyclic dependencies and packages will be initialized before their imports.
This PR implicitly merges the dependencies on the config package.
- cyclic dependency error message is displayed for the config package
- the config package can still import the configured package. This is necessary in order to use definitions from the configured package
This can break existing and working maps. So implementing the stricter cyclic dependency check as a warning may be preferred. At least for some time, similar to globals …
> detect cyclic dependencies caused by config packages 

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/WurstCompilerJassImpl.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/ConstantAndCopyPropagation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/ControlFlowGraph.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/LocalMerger.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/SideEffectAnalyzer.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/TempMerger.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/GlobalsInliner.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/ImCompressor.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/ImInliner.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/ImOptimizer.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/NullSetter.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtojass/ImAttrType.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ImHelper.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/UsedFunctions.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/UsedVariables.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/RemoveGarbage.java
lua translation does not eliminate as many constructs from the intermediate language as JASS. As a result, the optimizers need to support these constructs:
classes, methods, vararg loops
> optimizers for lua

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/ModelManagerImpl.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/ModelManagerTests.java
When changing a module in vscode, changes were not directly reflected in other files using the module. With this change, we now clear the module intantiations in depending packages so that they are recomputed on demand.
> Fix updating module instantiations in model manager

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/ReflectionNativeProvider.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/mocks/QuestItemMock.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/mocks/QuestMock.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/providers/QuestItemProvider.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/providers/QuestProvider.java
Natives which have some visible effect are mocked out (QuestSetCompleted, IsQuestCompleted, etc...). Others are just no-ops.
I couldn't find prior examples of how to test mocks for their correctness, so no unit tests are added to the repository. These changes were manually test with a local rebuild of the repository and running Wurstscript unit tests that rely on the mocks being available. The tests fail at HEAD and succeed with these changes.
Also didn't see a style guide, and Java is not my primary language. Suggestions are welcome!
> Add mocks for Quest and QuestItem natives.

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/parser/antlr/AntlrWurstParseTreeTransformer.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/ArrayTests.java
Addresses #998 .
rewrites
`test[getIndex()]++`
to
```
let tmp = getIndex()
test[tmp] = test[tmp] + 1
``` 
Few remarks:
- I rewrote transformStatement so it returns a list of statements rather than a single one in order to add the temporary variables before the set statement. Maybe there is a way to combine multiple statements in a single one?
- It assumes, indexes are integers. Since this transformation happens so early in the compiler, there doesn't seem to be a way to get the type of the index expressions. Should be fine though, because all array indexes are always integer.
- From a quick look, jurst seems to have the same code. I haven't updated it, but if this implementation is ok, I can apply it to jurst as well.
- I used tmpArrayIndex_ combined with the line number as name for the …
> Temporary index variable for shorthand assignments

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/WurstCompilerJassImpl.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/jassinterpreter/providers/LuaEnsureTypeProvider.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/ConstantAndCopyPropagation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/LocalMerger.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/intermediatelang/optimizer/TempMerger.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imoptimizer/ImOptimizer.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtojass/ImAttrType.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/EliminateLocalTypes.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ExprTranslation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/ImTranslator.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/ExprTranslation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/StmtTranslation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/types/TypesHelper.java
Bugfixes and improvements for Lua optimizers.
Implements some handling of tuples and members that was missing and could cause:
<details> 
<summary>Compiler error due to unattached variables, when doing some optimizations with tuples</summary>
-inline
-localOptimizations
-lua
```
package MyTest
function locals() returns bool
var d = vec2(1,0)
d.y = 2
return d.x == 1
init
if locals()
print("Success")
```
</details>
<details> 
<summary>Wrong output script due to incorrect assumptions by the optimizer </summary>
-inline
-localOptimizations
-lua
```
package ListSort
import LinkedList
init
let list = new LinkedList<int>()
list.add(1,2)
list.sort()
print(list.get(0))
print(list.get(1))
```
This prints 1 and 0. It is caused by the split function in LinkedList:
```
...
let tmp = halfRef.next …
```
> Improve Lua optimizers

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/EliminateLocalTypes.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/ExprTranslation.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/LuaTranslationTests.java
What I said [here](https://github.com/wurstscript/WurstScript/pull/1063#issuecomment-1179729151) with the enums working differently is wrong. I assumed so, because I saw objectToIndex being used for the cast.
What happened is that due to the local type elimination, the translator did not know it was a cast from int (Enum) to int and only saw a cast from something to int, so it inserted the objectToIndex.
Now these unnecessary casts from int to int are removed in advance, so that the translator does not need to know the type of the expression that's being cast and works with eliminated local types.
> Remove type dependency from cast translation

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/utils/W3InstallationData.java
It may be better to update w3utils to throw a different exception to match against for linux versus a not-found mac/windows one, but this seems like a sensible improvement anyway since wurstc just uses latest patch when the version cannot be determined.
To be clear, when this stacktrace appears, wurstc has no problem building a map successfully.
```
$ grill build base_map.w3x
🔥 Grill warming up..
🔥 Ready. Version: <1.3.4.1-jenkins-WurstSetup-157>
🔨 Building project..
java.nio.file.NoSuchFileException: /mnt/c/Users/Cokem/workspace/..././wurst/_build/dependencies
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at …
```
> warn log instead of printing stacktrace on linux platform

- de.peeeq.wurstscript/build.gradle
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/ProjectConfigBuilder.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/utils/W3InstallationData.java
```
$ grill build base_map.w3x
🔥 Grill warming up..
Custom WurstScript installation detected.
🔥 Ready. Version: <1.3.4.1-jenkins-WurstSetup-157>
🔨 Building project..
java.nio.file.NoSuchFileException: /mnt/c/Users/Cokem/workspace/kill-katydma/./wurst/_build/dependencies
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
at java.nio.file.Files.newDirectoryStream(Files.java:457)
at java.nio.file.Files.list(Files.java:3451)
at de.peeeq.wurstio.map.importer.ImportFile.getTransientImportDirectories(ImportFile.java:216)
at …
```
> Eliminate stacktrace when compiling on linux

- de.peeeq.wurstscript/parserspec/lua.parseq
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/ProjectConfigBuilder.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/MapRequest.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunMap.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/printing/LuaPrinter.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/ExprTranslation.java
- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/lua/translation/LuaTranslator.java
- Lua config is now applied to w3i even if no buildMapData is present
- Player config gets correctly injected into the script in lua mode
- Use `//` floor division operator for translating integer division
- Use `math.tointeger` to ensure correct representation of integers, aligning them with Jass
> Fix lua map config and number issues

- de.peeeq.wurstscript/src/main/java/de/peeeq/wurstscript/translation/imtranslation/RecycleCodeGeneratorQueue.java
- de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/WurstScriptTest.java
Fixes https://github.com/wurstscript/WurstScript/issues/1057
> Use JASS_MAX_ARRAY_SIZE for class allocation check
